// Demo data for a construction company
export const DEMO_DATA = {
  company: {
    name: 'Summit Construction Co.',
  },
  functions: [
    { name: 'Marketing', description: 'Lead generation and brand awareness', color: '#3B82F6', status: 'active' },
    { name: 'Sales', description: 'Converting leads to clients', color: '#10B981', status: 'active' },
    { name: 'Design', description: 'Project design and planning', color: '#F59E0B', status: 'draft' },
    { name: 'Estimating', description: 'Pricing and proposals', color: '#EF4444', status: 'gap' },
    { name: 'Production', description: 'Project execution and delivery', color: '#8B5CF6', status: 'draft' },
    { name: 'Finance', description: 'Accounting and cash flow', color: '#EC4899', status: 'active' },
    { name: 'Administration', description: 'Operations and support', color: '#06B6D4', status: 'gap' },
  ],
  subFunctions: {
    'Marketing': [
      { name: 'Brand Awareness', status: 'active' },
      { name: 'Lead Generation', status: 'draft' },
      { name: 'Content Marketing', status: 'gap' },
      { name: 'Referral Program', status: 'draft' },
    ],
    'Sales': [
      { name: 'Lead Qualification', status: 'active' },
      { name: 'Discovery', status: 'draft' },
      { name: 'Proposal Delivery', status: 'draft' },
      { name: 'Contract Signing', status: 'gap' },
    ],
    'Design': [
      { name: 'Initial Concepts', status: 'draft' },
      { name: 'Design Development', status: 'gap' },
      { name: 'Selections', status: 'draft' },
      { name: 'Final Plans', status: 'gap' },
    ],
    'Estimating': [
      { name: 'Material Takeoff', status: 'gap' },
      { name: 'Labor Estimation', status: 'gap' },
      { name: 'Vendor Quotes', status: 'draft' },
      { name: 'Proposal Building', status: 'draft' },
    ],
    'Production': [
      { name: 'Pre-Construction', status: 'draft' },
      { name: 'Rough-In', status: 'gap' },
      { name: 'Finishes', status: 'draft' },
      { name: 'Punch List', status: 'active' },
    ],
    'Finance': [
      { name: 'Invoicing', status: 'active' },
      { name: 'Collections', status: 'draft' },
      { name: 'Payroll', status: 'draft' },
      { name: 'Job Costing', status: 'gap' },
    ],
    'Administration': [
      { name: 'Scheduling', status: 'gap' },
      { name: 'Permits', status: 'draft' },
      { name: 'Insurance', status: 'gap' },
      { name: 'HR', status: 'draft' },
    ],
  },
  activities: {
    'Lead Generation': [
      { name: 'Run social media ads', status: 'active' },
      { name: 'Post to Houzz', status: 'draft' },
      { name: 'Send email newsletter', status: 'draft' },
      { name: 'Host open house', status: 'gap' },
    ],
    'Discovery': [
      { name: 'Schedule discovery call', status: 'active' },
      { name: 'Conduct site visit', status: 'draft' },
      { name: 'Document client requirements', status: 'draft' },
      { name: 'Review budget expectations', status: 'gap' },
    ],
    'Proposal Delivery': [
      { name: 'Present proposal in person', status: 'draft' },
      { name: 'Walk through scope', status: 'draft' },
      { name: 'Answer questions', status: 'gap' },
      { name: 'Handle objections', status: 'gap' },
    ],
    'Pre-Construction': [
      { name: 'Order materials', status: 'draft' },
      { name: 'Schedule subcontractors', status: 'draft' },
      { name: 'Create project schedule', status: 'gap' },
      { name: 'Hold pre-con meeting', status: 'gap' },
    ],
    'Punch List': [
      { name: 'Create punch list', status: 'active' },
      { name: 'Complete punch items', status: 'draft' },
      { name: 'Schedule final walk', status: 'draft' },
      { name: 'Obtain sign-off', status: 'active' },
    ],
  },
  workflows: [
    {
      name: 'Client Journey',
      description: 'End-to-end client experience from lead to completion',
      status: 'active',
      publishedAt: '2025-11-12T15:00:00.000Z',
      phases: [
        { name: 'Lead', steps: ['Capture lead info', 'Send intro email', 'Qualify lead'] },
        { name: 'Discovery', steps: ['Schedule call', 'Conduct site visit', 'Document needs'] },
        { name: 'Proposal', steps: ['Build estimate', 'Create proposal', 'Present to client'] },
        { name: 'Contract', steps: ['Send contract', 'Collect deposit', 'Schedule kickoff'] },
        { name: 'Production', steps: ['Pre-construction', 'Execute work', 'Quality checks'] },
        { name: 'Completion', steps: ['Final walk', 'Collect final payment', 'Request review'] },
      ],
    },
    {
      name: 'Sales Process',
      description: 'Converting leads to signed contracts',
      status: 'draft',
      phases: [
        { name: 'Qualify', steps: ['Review lead source', 'Check budget fit', 'Assess project scope'] },
        { name: 'Discover', steps: ['Schedule discovery', 'Site visit', 'Document requirements'] },
        { name: 'Propose', steps: ['Build estimate', 'Package proposal', 'Present'] },
        { name: 'Close', steps: ['Handle objections', 'Negotiate terms', 'Sign contract'] },
      ],
    },
  ],
  people: [
    { name: 'Mike Johnson', email: 'mike@summit.com', role: 'Owner' },
    { name: 'Sarah Chen', email: 'sarah@summit.com', role: 'Project Manager' },
    { name: 'Tom Williams', email: 'tom@summit.com', role: 'Sales Rep' },
    { name: 'Lisa Garcia', email: 'lisa@summit.com', role: 'Designer' },
    { name: 'James Brown', email: 'james@summit.com', role: 'Estimator' },
  ],
  roles: [
    { name: 'Owner', description: 'Business owner and final decision maker' },
    { name: 'Project Manager', description: 'Oversees project execution' },
    { name: 'Sales Rep', description: 'Handles client acquisition' },
    { name: 'Designer', description: 'Creates project designs' },
    { name: 'Estimator', description: 'Builds estimates and proposals' },
    { name: 'Admin', description: 'Handles administrative tasks' },
  ],
  software: [
    { name: 'HubSpot', url: 'https://hubspot.com' },
    { name: 'BuilderTrend', url: 'https://buildertrend.com' },
    { name: 'QuickBooks', url: 'https://quickbooks.com' },
    { name: 'Chief Architect', url: 'https://chiefarchitect.com' },
    { name: 'Google Workspace', url: 'https://workspace.google.com' },
  ],
}
