import '@testing-library/jest-dom/vitest'
import { vi } from 'vitest'

// Mock Supabase client to avoid env var requirements in tests
vi.mock('@/lib/supabase/client', () => ({
  supabase: {
    from: vi.fn(() => ({
      select: vi.fn().mockReturnThis(),
      insert: vi.fn().mockReturnThis(),
      update: vi.fn().mockReturnThis(),
      delete: vi.fn().mockReturnThis(),
      eq: vi.fn().mockReturnThis(),
      order: vi.fn().mockReturnThis(),
      single: vi.fn().mockResolvedValue({ data: null, error: null }),
    })),
  },
}))

// Mock sync functions
vi.mock('@/lib/supabase/sync', () => ({
  fetchWorkspaces: vi.fn().mockResolvedValue([]),
  createWorkspace: vi.fn().mockResolvedValue({}),
  updateWorkspace: vi.fn().mockResolvedValue({}),
  deleteWorkspace: vi.fn().mockResolvedValue(undefined),
  fetchFunctions: vi.fn().mockResolvedValue([]),
  createFunction: vi.fn().mockResolvedValue({}),
  updateFunction: vi.fn().mockResolvedValue({}),
  deleteFunction: vi.fn().mockResolvedValue(undefined),
  updateFunctionOrder: vi.fn().mockResolvedValue(undefined),
  fetchSubFunctions: vi.fn().mockResolvedValue([]),
  createSubFunction: vi.fn().mockResolvedValue({}),
  updateSubFunction: vi.fn().mockResolvedValue({}),
  deleteSubFunction: vi.fn().mockResolvedValue(undefined),
  updateSubFunctionOrder: vi.fn().mockResolvedValue(undefined),
  fetchActivities: vi.fn().mockResolvedValue([]),
  createActivity: vi.fn().mockResolvedValue({}),
  updateActivity: vi.fn().mockResolvedValue({}),
  deleteActivity: vi.fn().mockResolvedValue(undefined),
  fetchChecklistItems: vi.fn().mockResolvedValue([]),
  createChecklistItem: vi.fn().mockResolvedValue({}),
  updateChecklistItem: vi.fn().mockResolvedValue({}),
  deleteChecklistItem: vi.fn().mockResolvedValue(undefined),
  updateChecklistItemOrder: vi.fn().mockResolvedValue(undefined),
  fetchWorkflows: vi.fn().mockResolvedValue([]),
  createWorkflow: vi.fn().mockResolvedValue({}),
  updateWorkflow: vi.fn().mockResolvedValue({}),
  deleteWorkflow: vi.fn().mockResolvedValue(undefined),
  fetchPhases: vi.fn().mockResolvedValue([]),
  createPhase: vi.fn().mockResolvedValue({}),
  updatePhase: vi.fn().mockResolvedValue({}),
  deletePhase: vi.fn().mockResolvedValue(undefined),
  updatePhaseOrder: vi.fn().mockResolvedValue(undefined),
  fetchSteps: vi.fn().mockResolvedValue([]),
  createStep: vi.fn().mockResolvedValue({}),
  updateStep: vi.fn().mockResolvedValue({}),
  deleteStep: vi.fn().mockResolvedValue(undefined),
  updateStepOrder: vi.fn().mockResolvedValue(undefined),
  fetchPeople: vi.fn().mockResolvedValue([]),
  createPerson: vi.fn().mockResolvedValue({}),
  updatePerson: vi.fn().mockResolvedValue({}),
  deletePerson: vi.fn().mockResolvedValue(undefined),
  fetchRoles: vi.fn().mockResolvedValue([]),
  createRole: vi.fn().mockResolvedValue({}),
  updateRole: vi.fn().mockResolvedValue({}),
  deleteRole: vi.fn().mockResolvedValue(undefined),
  fetchSoftware: vi.fn().mockResolvedValue([]),
  createSoftware: vi.fn().mockResolvedValue({}),
  updateSoftware: vi.fn().mockResolvedValue({}),
  deleteSoftware: vi.fn().mockResolvedValue(undefined),
}))
